import {style} from 'typestyle';

const styles = {
    Background: style({
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        alignSelf: 'center',
        minWidth: 'auto',
        maxWidth: 'auto',
        height: '120px',
        padding: '16px 124px 24px 125px',
        backgroundColor: '#00a9e0',
    }),
    TopText: style({
        width: '110px',
        height: '16px',
        padding: '14px 0 0 0',
        margin: '0 0 6px',
        fontFamily: 'Roboto',
        fontSize: '12px',
        fontWeight: 'bold',
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 1.33,
        letterSpacing: 'normal',
        textAlign: 'center',
        color: '#ffffff',
    }),
    MidText: style({
        width: '91px',
        height: '24px',
        margin: '14px 10px 10px 9px',
        fontFamily: 'Roboto',
        fontSize: '20px',
        fontWeight: 500,
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 1.2,
        letterSpacing: 'normal',
        textAlign: 'center',
        color: '#ffffff',
    }),
    BottomText: style({
        width: '108px',
        height: '16px',
        margin: '12px 1px 0',
        fontFamily: 'Roboto',
        fontSize: '12px',
        fontWeight: 'bold',
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 1.33,
        letterSpacing: 'normal',
        textAlign: 'center',
        color: '#ffffff',
    }),
};

export default styles;